# System-wide Stack configuration #

local-bin-path: .local/bin

arch: x86_64

system-ghc: false
install-ghc: true

ghc-options:
    "$locals": -Wall
    "$targets": -Werror
    "$everything": -O2

apply-ghc-options: locals
rebuild-ghc-options: true

templates:
    params:
        author-email: damien.flament@gmx.com
        author-name: Damien Flament
        github-username: damienflament

