import os
from pathlib import Path

from assertpy import add_extension
from attrs import define
from hypothesis import HealthCheck, Verbosity, settings
from pytest import fixture
from pytestshellutils.shell import ProcessResult

# Ajoute le dossier des scripts testés au *PATH* pour qu'ils puissent être
# exécutés.
os.environ["PATH"] = (
    str(Path(__file__).parent.parent) + os.pathsep + os.environ["PATH"]
)


# Extensions shell pour assertpy
# TODO Créer un plugin assertpy + pytest-shell-extension
def check_is_command_result(value):
    """Vérifie que la valeur est bien le résultat d'un appel à
    `shell.run()`."""
    if not isinstance(value, ProcessResult):
        raise TypeError("value is not a shell command result")


def ensure_command_result_was_checked(value):
    """Vérifie que le résultat de la commande a déjà été vérifié."""
    if not hasattr(value, "_command_result"):
        raise AssertionError(
            "the command result wasn't checked: call `succeeds()` or "
            "`fails()` first"
        )


def succeeds(self):
    """Vérifie que la valeur est le résultat d'une commande et que celle-ci
    s'est correctement terminée."""
    check_is_command_result(self.val)
    self._command_result = self.val

    if self.val.returncode != 0:
        return self.error(
            f"command failed with {self.val.returncode}"
            f" and printed to stderr: {self.val.stderr.strip()}"
        )

    return self


def fails(self):
    """Vérifie que la valeur est le résultat d'une commande et que celle-ci
    s'est terminée par une erreur."""
    check_is_command_result(self.val)
    self._command_result = self.val

    if self.val.returncode == 0:
        return self.error("command didn't fail")

    return self


def and_status(self):
    """Change le sujet des vérifications pour le code de status de la
    commande."""
    ensure_command_result_was_checked(self)

    self.val = self._command_result.returncode

    return self


def and_stdout(self):
    """Change le sujet des vérifications pour la sortie standard de la
    commande."""
    ensure_command_result_was_checked(self)

    self.val = self._command_result.stdout.strip()

    return self


def and_stderr(self):
    """Change le sujet des vérifications pour la sortie d'erreur standard de la
    commande."""
    ensure_command_result_was_checked(self)

    self.val = self._command_result.stderr.strip()

    return self


add_extension(succeeds)
add_extension(fails)
add_extension(and_status)
add_extension(and_stdout)
add_extension(and_stderr)


# TODO Créer un plugin cmd-mocker
@define
class CommandMocker:
    """Mocker de commandes shell."""

    _directory: Path

    def __attrs_post_init__(self):
        self._directory.mkdir()

    def patch(
        self,
        name: str,
        returns: int = 0,
        outputs: str = None,
        errors: str = None,
    ):
        """Patche une commande shell.

        Un script POSIX shell est créé pour la commande spécifiée. Ce script
        est rendu exécutable.

        La commande retourne la valeur spécifiée (:term:`0` par défaut) et
        imprime les chaînes spécifiées sur la sortie standard et la sortie
        d'erreur.
        """

        f = self._directory / name

        content = "#!/bin/sh\n"
        "# File generated by {__file__}:patch_shell_command\n"

        if outputs is not None:
            content += f"echo '{outputs}'\n"

        if errors is not None:
            content += f"echo '{errors}' >&2\n"

        content += f"exit {returns}\n"

        f.touch()
        f.write_text(content)
        f.chmod(0o755)


@fixture
def cmd_mocker(tmp_path, shell):
    """Fournit un mocker de commandes shell.

    Les mocks sont des scripts POSIX shell créés dans un dossier *bin* situé
    dans le dossier temporaire fourni par la fixture *tmp_path*.

    Ce dossier *bin/* est ajouté au *PATH* de la fixture *shell* afin que les
    commandes appelées via *sell.run()* utilisent les mocks.
    """
    # L'utilisation de la fixture *tmp_path* garantit qu'un dossier
    # temporaire unique est utilisé pour chaque test et que celui-ci sera
    # également utilisé par la fonction de test si elle fait appel à la même
    # fixture.
    #
    # De la même manière, ce dossier est ajouté au *PATH* de l'environnement
    # d'exécution de la fixture *shell*. Comme la fixture *shell* n'est
    # initialisée qu'une seule fois par session, il est nécessaire de remettre
    # le *PATH* dans son état initial afin d'éviter que les mocks ne soient
    # disponibles durant le test suivant
    bin_directory = tmp_path / "bin"

    shell.environ["PATH"] = (
        str(bin_directory) + os.pathsep + shell.environ["PATH"]
    )

    yield CommandMocker(bin_directory)

    paths = shell.environ["PATH"].split(os.pathsep)
    paths.remove(str(bin_directory))
    shell.environ["PATH"] = os.pathsep.join(paths)
